# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: leaddb
    volumes:
       - ./data:/var/lib/postgresql/data
       #data gets backed up in data folder in the same path
    ports:
       - 5432:5432
       
    